AllCops:
  Include:
    - Gemfile
    - Rakefile
    - bootstrap
    - script/console
    - '**/*.rb'
  Exclude:
    - bin/*
    - vendor/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Style/GlobalVars:
  Exclude:
    - script/console
