#!/usr/bin/env ruby
# frozen_string_literal: true

require 'pathname'

lib_dir = Pathname(__dir__).join('lib').expand_path
config_dir = Pathname(__dir__).join('config').expand_path
messages_file = config_dir.join('messages.yml').open
qualifications_file = config_dir.join('qualifications.yml').open
colaborators_file = config_dir.join('colaborators.yml').open

$LOAD_PATH.unshift lib_dir
require 'umts_training'

local_repo = UMTSTraining::LocalRepo.new Pathname(__dir__)
cli = UMTSTraining::CLI.new messages_file

cli.message :create_client
client = UMTSTraining::Client.new local_repo, cli
milestone = UMTSTraining::Milestone.new local_repo,
                                        client,
                                        qualifications_file

cli.message :add_collabs
colaborators = YAML.safe_load colaborators_file
client.add_collaborators! colaborators

cli.message :create_issues
milestone.create!
milestone.create_issues!

cli.message :done

messages_file.close
qualifications_file.close
colaborators_file.close
