#!/usr/bin/env ruby
this_dir = File.dirname(__FILE__)

$LOAD_PATH.unshift File.join(this_dir, 'lib')
require 'umts_training'

local_repo = UMTSTraining::LocalRepo.new this_dir
cli = UMTSTraining::CLI.new 'messages.yml'

cli.message 'create_client'
client = UMTSTraining::Client.new local_repo, cli
milestone = UMTSTraining::Milestone.new local_repo,
                                        client,
                                        'qualifications.yml'

cli.message 'add_collabs'
client.add_collaborators! UMTSTraining.collaborators

cli.message 'create_issues'
milestone.create!
milestone.create_issues!

cli.message 'done'
