---
title: Configure your laptop for development
description: >
  go to https://strap.umasstransit.it/ and follow the instructions.
---
title: Set up GitHub
description: >
  [Login to or sign up for GitHub.](https://github.com/)
subtasks:
  - Set up two-factor authentication.
  - Tell us your username so we can add you to our organization.
  - Your notification settings for GitHub can be found [here](https://github.com/settings/notifications).
    The minimum we require is that you have 'Email' checked under the header 'Participating'.
  - You should clone repositories using the SSH URL from now on. Please follow the instructions
    for [connecting to GitHub using SSH](https://help.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh).
---
title: Read through documents related to university owned computers
description: >
  Since you will be trusted with university-owned computers and potentially
  sensitive data, you should review these documents
subtasks:
  - '[Security Checklist](https://www.umass.edu/it/support/security/security-checklist-university-owned-computers)'
  - '[Understanding Sensitive Data](https://www.umass.edu/it/support/security/understand-sensitive-data-umass-amherst)'
  - '[Data Classification](https://www.umass.edu/it/support/security/data-classification-umass-amherst)'
---
title: Read the transportation programmer policies
description: >
  This document lives in our programmer training [box folder](https://umass.app.box.com/folder/77237337598)
---
title: Join Slack
description: >
  We use [Slack](https://slack.com/) for communication every day. After your invitation to our
  Slack team, you can download the desktop version or use the web version, whichever suits you.
---
title: Choose a text editor
description: >
  We don't care what text editor you use. However, we do have some suggestions.
  Other people in the office have used [atom](https://atom.io/), [sublime](https://www.sublimetext.com/3)...
  and [Vim](https://www.tutorialspoint.com/vim/vim_introduction.htm). Vim is already installed on your laptop,
  so if you'd like a quick introduction, type `vimtutor` in your terminal.
---
title: Complete a command line tutorial
description: >
  Having a good grasp of the command line is essential for working in our team,
  as we use the command line every single day for various tasks
  Use the first couple chapters of [this tutorial](https://www.learnenough.com/command-line-tutorial/basics)
  or another approved tutorial to brush up on your basics, and link to it in a
  comment to close this issue.
---
title: Complete a git tutorial
description: >
  We use Git in combination with Github to work collaboratively on our code.
  Log in to O'Reilly's learning tools for free with your UMass account and
  complete [this](https://learning.oreilly.com/videos/essential-git/200000006A0403)
  or another approved tutorial and link to it in a comment to close this issue.
---
title: Complete a Rails Tutorial
description: >
  The current tutorial in use is Michael Hartl's [Ruby on Rails Tutorial](https://learning.oreilly.com/library/view/ruby-on-rails/9780136702726/).
  Log in for free using your UMass account to O'Reilly or, if you wish to use an alternate tutorial, talk to your supervisor.

  You can follow the tutorial pretty closely, except for the following caveats below.
  - In section 1.1.1 "Development environment", don't set up cloud9.
    Your laptop has been set up with a development environment.
  - In section 1.4.1 "Heroku setup and Deployment", there are instructions to set up a Heroku account to deploy your code to.
    Since you'll be deploying code to production in a few short months, you can skip setting up a heroku account
    and all related steps.
---
title: Complete a ruby tutorial
description: >
  There are many Ruby tutorials available which you can choose from. Log in for
  free using your UMass account and watch [these videos](https://learning.oreilly.com/videos/ruby-fundamentals/300000006A0154),
  or you can download the [Ruby Koans](http://rubykoans.com/). If neither of those
  options appeal to you you may choose another tutorial with your supervisor's approval.
---
title: Demonstrate understanding of Ruby core methods / Rails object extensions
description: >
  Some methods used in our Rails applications are Ruby methods. Some are
  written in Rails, like `try` and `1.week`. Close this issue by referencing
  some work where you have used both (can be two separate projects).
---
title: Understand the basics of databases and models and their relationship
description: >
  Write a migration and use a model relationship correctly.
---
title: Understand how to employ ActiveRecord
description: https://guides.rubyonrails.org/active_record_querying.html
subtasks:
  - Use `joins` or `includes`
  - Use `order` or `sort`
  - Use `where`, `find`, or `find_by` and explain the differences between these three
---
title: Have demonstrated familiarity with MVC architecture and the Rails asset pipeline
subtasks:
  - Demonstrate or explain that you know when to place logic in a controller and model,
    and what logic does _not_ go in a view.
  - Use a partial
  - Demonstrate understanding of how to use routes (a link, a redirect, or creating routes)
  - Use params in a controller
---
title: Demonstrate understanding of correct and proper git usage
description: >
  Show that you understand how to properly use Git by writing commits that
  generally relate to atomic features or thoughts. Make sure you know how to
  resolve a merge conflict correctly.
---
title: Submit a pull request for review
description: >
  Use effective descriptions that provide context of code and rationale for change.
  Tag some related issues.
---
title: have given feedback on another programmers code
description: >
  Ask helpful questions/suggest alternatives on someone else's code
---
title: display a good understanding of how and why to write tests
description: >
  Demonstrate knowledge of basic model/controller/system test structure.
  Demonstrate understanding of mocks/stubs and what purpose they serve.
---
title: Display an understanding of front-end development
description: >
  Use CSS to apply styling to pages, and construct some HAML or ERB. Select
  DOM elements using JQuery.
