#!/bin/sh

set -e
[ -z "$DEBUG" ] || set -x

cd "$(dirname "$0")/.."

if [ -n "$CI" ]; then
  /usr/bin/env ruby script/setup
else
  /usr/bin/env ruby script/update
fi

echo "==> Running tests..."
bin/rake
